// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SocialX.Infra.Data;

#nullable disable

namespace SocialX.Infra.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    partial class CustomDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SocialX.Core.Entidades.Amizade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DataResposta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_resposta");

                    b.Property<DateTime>("DataSolicitacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_solicitacao")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<long>("PessoaDestinoId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_destino_id");

                    b.Property<long>("PessoaOrigemId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_origem_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PessoaDestinoId")
                        .HasDatabaseName("ix_amizade_destino");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_amizade_status");

                    b.HasIndex("PessoaOrigemId", "PessoaDestinoId")
                        .IsUnique()
                        .HasDatabaseName("uq_amizade_origem_destino");

                    b.ToTable("amizade", (string)null);
                });

            modelBuilder.Entity("SocialX.Core.Entidades.Denuncia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AlvoId")
                        .HasColumnType("bigint")
                        .HasColumnName("alvo_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<long>("DenunciantePessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("denunciante_pessoa_id");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("motivo");

                    b.Property<DateTime?>("ResolvidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolvido_em");

                    b.Property<long?>("ResolvidoPorAdminId")
                        .HasColumnType("bigint")
                        .HasColumnName("resolvido_por_admin_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Aberta")
                        .HasColumnName("status");

                    b.Property<string>("TipoAlvo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_alvo");

                    b.HasKey("Id");

                    b.HasIndex("DenunciantePessoaId")
                        .HasDatabaseName("ix_denuncia_denunciante");

                    b.HasIndex("ResolvidoPorAdminId");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_denuncia_status");

                    b.HasIndex("TipoAlvo", "AlvoId")
                        .HasDatabaseName("ix_denuncia_alvo");

                    b.ToTable("denuncia", (string)null);
                });

            modelBuilder.Entity("SocialX.Core.Entidades.EntidadeTeste", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("EntidadeTeste", (string)null);
                });

            modelBuilder.Entity("SocialX.Core.Entidades.Evento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("CapacidadeMaxima")
                        .HasColumnType("integer")
                        .HasColumnName("capacidade_maxima");

                    b.Property<long>("CriadoPorPessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("criado_por_pessoa_id");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<DateTime?>("DataHoraFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_fim");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_inicio");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Endereco")
                        .HasColumnType("text")
                        .HasColumnName("endereco");

                    b.Property<long?>("GrupoId")
                        .HasColumnType("bigint")
                        .HasColumnName("grupo_id");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<string>("LinkOnline")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("link_online");

                    b.Property<string>("LocalNome")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("local_nome");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Privacidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("privacidade");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Ativo")
                        .HasColumnName("status");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Presencial")
                        .HasColumnName("tipo_evento");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorPessoaId")
                        .HasDatabaseName("ix_evento_criado_por");

                    b.HasIndex("DataHoraInicio")
                        .HasDatabaseName("ix_evento_data_inicio");

                    b.HasIndex("GrupoId")
                        .HasDatabaseName("ix_evento_grupo");

                    b.HasIndex("Privacidade")
                        .HasDatabaseName("ix_evento_privacidade");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_evento_status");

                    b.HasIndex("TipoEvento")
                        .HasDatabaseName("ix_evento_tipo");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("ix_evento_latitude_longitude");

                    b.ToTable("evento", (string)null);
                });

            modelBuilder.Entity("SocialX.Core.Entidades.Grupo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CriadoPorPessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("criado_por_pessoa_id");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("FotoCapa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("foto_capa");

                    b.Property<string>("FotoPerfil")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("foto_perfil");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Regras")
                        .HasColumnType("text")
                        .HasColumnName("regras");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Ativo")
                        .HasColumnName("status");

                    b.Property<string>("TipoPrivacidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_privacidade");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorPessoaId")
                        .HasDatabaseName("ix_grupo_criado_por");

                    b.HasIndex("DataCriacao")
                        .IsDescending()
                        .HasDatabaseName("ix_grupo_data_criacao");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_grupo_status");

                    b.HasIndex("TipoPrivacidade")
                        .HasDatabaseName("ix_grupo_tipo_privacidade");

                    b.HasIndex("TipoPrivacidade", "Status")
                        .HasDatabaseName("ix_grupo_tipo_status");

                    b.ToTable("grupo", (string)null);
                });

            modelBuilder.Entity("SocialX.Core.Entidades.GrupoMembro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AprovadoPorPessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("aprovado_por_pessoa_id");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_aprovacao");

                    b.Property<DateTime>("DataEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_entrada")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<long>("GrupoId")
                        .HasColumnType("bigint")
                        .HasColumnName("grupo_id");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AprovadoPorPessoaId");

                    b.HasIndex("PessoaId")
                        .HasDatabaseName("ix_grupo_membro_pessoa");

                    b.HasIndex("GrupoId", "PessoaId")
                        .IsUnique()
                        .HasDatabaseName("uq_grupo_membro");

                    b.ToTable("grupo_membro", (string)null);
                });

            modelBuilder.Entity("SocialX.Core.Entidades.GrupoModerador", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<long>("GrupoId")
                        .HasColumnType("bigint")
                        .HasColumnName("grupo_id");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("papel");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId")
                        .HasDatabaseName("ix_grupo_moderador_pessoa");

                    b.HasIndex("GrupoId", "PessoaId")
                        .IsUnique()
                        .HasDatabaseName("uq_grupo_moderador");

                    b.ToTable("grupo_moderador", (string)null);
                });

            modelBuilder.Entity("SocialX.Core.Entidades.LoginSocial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataVinculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vinculo")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("EmailProvider")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email_provider");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_user_id");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId")
                        .HasDatabaseName("ix_login_social_pessoa");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique()
                        .HasDatabaseName("uq_login_social_provider_user");

                    b.ToTable("login_social", (string)null);
                });

            modelBuilder.Entity("SocialX.Core.Entidades.Midia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataUpload")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_upload")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<long>("DonoId")
                        .HasColumnType("bigint")
                        .HasColumnName("dono_id");

                    b.Property<int?>("DuracaoSegundos")
                        .HasColumnType("integer")
                        .HasColumnName("duracao_segundos");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<int>("Ordem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("ordem");

                    b.Property<long?>("TamanhoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_bytes");

                    b.Property<string>("TipoArquivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_arquivo");

                    b.Property<string>("TipoDono")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_dono");

                    b.Property<string>("UrlArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_arquivo");

                    b.Property<string>("UrlThumbnail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_thumbnail");

                    b.HasKey("Id");

                    b.HasIndex("TipoArquivo")
                        .HasDatabaseName("ix_midia_tipo_arquivo");

                    b.HasIndex("TipoDono", "DonoId")
                        .HasDatabaseName("ix_midia_dono");

                    b.ToTable("midia", (string)null);
                });

            modelBuilder.Entity("SocialX.Core.Entidades.Notificacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_envio")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<bool>("Lida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("lida");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensagem");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<long?>("ReferenciaId")
                        .HasColumnType("bigint")
                        .HasColumnName("referencia_id");

                    b.Property<string>("ReferenciaTipo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("referencia_tipo");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId")
                        .HasDatabaseName("ix_notificacao_pessoa");

                    b.HasIndex("PessoaId", "Lida")
                        .HasDatabaseName("ix_notificacao_pessoa_lida");

                    b.ToTable("notificacao", (string)null);
                });

            modelBuilder.Entity("SocialX.Core.Entidades.ParticipacaoEvento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataResposta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_resposta")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<long>("EventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<string>("StatusParticipacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_participacao");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId")
                        .HasDatabaseName("ix_participacao_evento_pessoa");

                    b.HasIndex("EventoId", "PessoaId")
                        .IsUnique()
                        .HasDatabaseName("uq_participacao_evento");

                    b.ToTable("participacao_evento", (string)null);
                });

            modelBuilder.Entity("SocialX.Core.Entidades.Pessoa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("apelido");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("Cidade")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("cidade");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FotoPerfil")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("foto_perfil");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Usuario")
                        .HasColumnName("role");

                    b.Property<string>("StatusConta")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Ativa")
                        .HasColumnName("status_conta");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acesso");

                    b.HasKey("Id");

                    b.HasIndex("Apelido")
                        .IsUnique()
                        .HasDatabaseName("uq_pessoa_apelido");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_pessoa_email");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_pessoa_nome");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_pessoa_role");

                    b.HasIndex("StatusConta")
                        .HasDatabaseName("ix_pessoa_status_conta");

                    b.ToTable("pessoa", (string)null);
                });

            modelBuilder.Entity("SocialX.Core.Entidades.Post", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AutorPessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("autor_pessoa_id");

                    b.Property<DateTime?>("DataEdicao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_edicao");

                    b.Property<DateTime>("DataPublicacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_publicacao")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<long?>("EventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<bool>("Fixado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("fixado");

                    b.Property<long?>("GrupoId")
                        .HasColumnType("bigint")
                        .HasColumnName("grupo_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Ativo")
                        .HasColumnName("status");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.Property<string>("Titulo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("titulo");

                    b.Property<string>("Visibilidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visibilidade");

                    b.HasKey("Id");

                    b.HasIndex("AutorPessoaId")
                        .HasDatabaseName("ix_post_autor");

                    b.HasIndex("DataPublicacao")
                        .IsDescending()
                        .HasDatabaseName("ix_post_data_publicacao");

                    b.HasIndex("EventoId")
                        .HasDatabaseName("ix_post_evento");

                    b.HasIndex("GrupoId")
                        .HasDatabaseName("ix_post_grupo");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_post_status");

                    b.HasIndex("Visibilidade")
                        .HasDatabaseName("ix_post_visibilidade");

                    b.ToTable("post", (string)null);
                });

            modelBuilder.Entity("SocialX.Core.Entidades.Amizade", b =>
                {
                    b.HasOne("SocialX.Core.Entidades.Pessoa", "PessoaDestino")
                        .WithMany()
                        .HasForeignKey("PessoaDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialX.Core.Entidades.Pessoa", "PessoaOrigem")
                        .WithMany()
                        .HasForeignKey("PessoaOrigemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PessoaDestino");

                    b.Navigation("PessoaOrigem");
                });

            modelBuilder.Entity("SocialX.Core.Entidades.Denuncia", b =>
                {
                    b.HasOne("SocialX.Core.Entidades.Pessoa", "Denunciante")
                        .WithMany()
                        .HasForeignKey("DenunciantePessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialX.Core.Entidades.Pessoa", "ResolvidoPor")
                        .WithMany()
                        .HasForeignKey("ResolvidoPorAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Denunciante");

                    b.Navigation("ResolvidoPor");
                });

            modelBuilder.Entity("SocialX.Core.Entidades.Evento", b =>
                {
                    b.HasOne("SocialX.Core.Entidades.Pessoa", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorPessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialX.Core.Entidades.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CriadoPor");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("SocialX.Core.Entidades.Grupo", b =>
                {
                    b.HasOne("SocialX.Core.Entidades.Pessoa", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorPessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CriadoPor");
                });

            modelBuilder.Entity("SocialX.Core.Entidades.GrupoMembro", b =>
                {
                    b.HasOne("SocialX.Core.Entidades.Pessoa", "AprovadoPor")
                        .WithMany()
                        .HasForeignKey("AprovadoPorPessoaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SocialX.Core.Entidades.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialX.Core.Entidades.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AprovadoPor");

                    b.Navigation("Grupo");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("SocialX.Core.Entidades.GrupoModerador", b =>
                {
                    b.HasOne("SocialX.Core.Entidades.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialX.Core.Entidades.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("SocialX.Core.Entidades.LoginSocial", b =>
                {
                    b.HasOne("SocialX.Core.Entidades.Pessoa", "Pessoa")
                        .WithMany("LoginsSociais")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("SocialX.Core.Entidades.Notificacao", b =>
                {
                    b.HasOne("SocialX.Core.Entidades.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("SocialX.Core.Entidades.ParticipacaoEvento", b =>
                {
                    b.HasOne("SocialX.Core.Entidades.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialX.Core.Entidades.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("SocialX.Core.Entidades.Post", b =>
                {
                    b.HasOne("SocialX.Core.Entidades.Pessoa", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorPessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialX.Core.Entidades.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SocialX.Core.Entidades.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Autor");

                    b.Navigation("Evento");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("SocialX.Core.Entidades.Pessoa", b =>
                {
                    b.Navigation("LoginsSociais");
                });
#pragma warning restore 612, 618
        }
    }
}
